/**
 * Bash special builtin variables that must NOT be resolved via process.env
 * fallback. These variables are either dynamically generated by bash at each
 * reference (e.g. RANDOM, LINENO), reflect internal shell state (e.g. BASH_SOURCE,
 * FUNCNAME), or are positional parameters — none of which can be correctly
 * resolved by looking at the language server's own environment variables.
 *
 * For these variables, the flow analysis must either track them internally
 * (e.g. PWD via cd/pushd/popd, BASH_SOURCE[0] as the current file) or return
 * unknown/unknowable values.
 */

/**
 * Variables that bash generates dynamically on every reference.
 * Their values change each time they are expanded and cannot be predicted
 * statically. Falling back to process.env is incorrect — if set in env at
 * all, the value would be stale or meaningless.
 */
export const DYNAMIC_BUILTIN_VARIABLES = new Set([
  'RANDOM',
  'SRANDOM',
  'SECONDS',
  'EPOCHSECONDS',
  'EPOCHREALTIME',
  'BASH_MONOSECONDS',
  'BASHPID',
  'LINENO',
])

/**
 * Variables that reflect bash shell state. These are maintained internally
 * by bash and are never exported to the environment by default.
 */
export const BASH_STATE_VARIABLES = new Set([
  // Bash info
  'BASH',
  'BASHOPTS',
  'BASH_ALIASES',
  'BASH_ARGC',
  'BASH_ARGV',
  'BASH_CMDS',
  'BASH_COMMAND',
  'BASH_EXECUTION_STRING',
  'BASH_LINENO',
  'BASH_LOADABLES_PATH',
  'BASH_REMATCH',
  'BASH_SOURCE',
  'BASH_SUBSHELL',
  'BASH_VERSINFO',
  'BASH_VERSION',

  // Call stack
  'FUNCNAME',
  'FUNCNEST',

  // Shell state
  'OLDPWD',
  'PPID',
  'SHELLOPTS',
  'SHLVL',
  'UID',
  'EUID',
  'GROUPS',

  // Arrays
  'DIRSTACK',
  'PIPESTATUS',

  // History
  'HISTCMD',
  'HISTFILE',
  'HISTFILESIZE',
  'HISTSIZE',

  // Completion (rarely needed but definitely not env vars)
  'COMP_WORDS',
  'COMP_CWORD',
  'COMP_LINE',
  'COMP_POINT',
  'COMP_TYPE',
  'COMP_KEY',
  'COMP_REPLY',

  // Misc
  'CHILD_MAX',
  'BASH_COMPAT',
  'ENV',
  'HOSTFILE',
  'HOSTNAME',
  'HOSTTYPE',
  'MACHTYPE',
  'OSTYPE',
  'PROMPT_COMMAND',
  'PROMPT_DIRTRIM',
  'PS0',
  'PS1',
  'PS2',
  'PS3',
  'PS4',
  'SHELL',
  'TIMEFORMAT',
  'TMOUT',
  'TMPDIR',
  'auto_resume',
])

/**
 * Positional parameters and special shell parameters.
 * $0 through $9, $#, $?, $!, $-, $_, $$, $@, $*
 * These are purely internal to the shell and must never resolve via env.
 */
export const SPECIAL_PARAMETERS = new Set([
  '@',
  '*',
  '#',
  '?',
  '!',
  '-',
  '$',
  '_',
  '0',
  ...Array.from({ length: 9 }, (_, i) => String(i + 1)),
])

/**
 * Variable names that are tracked by flow analysis and may have known
 * initial values seeded at the start of script analysis.
 */
export const TRACKED_BUILTIN_VARIABLES = new Set([
  'PWD',
  'OLDPWD',
  'DIRSTACK',
  'BASH_SOURCE',
  'FUNCNAME',
])

/**
 * The complete set of all bash builtin variable names that should
 * never fall back to process.env resolution.
 */
export const ALL_BUILTIN_VARIABLES = new Set([
  ...DYNAMIC_BUILTIN_VARIABLES,
  ...BASH_STATE_VARIABLES,
  ...SPECIAL_PARAMETERS,
  // PWD is tracked by flow analysis (cd/pushd/popd) and seeded from cwd
  'PWD',
])

/**
 * Returns true if the variable name is a bash builtin (special/dynamic/positional)
 * that should NEVER fall back to process.env.
 */
export function isBashBuiltinVariable(varName: string): boolean {
  return ALL_BUILTIN_VARIABLES.has(varName)
}

/**
 * Returns true if the variable name is a dynamically-generated bash variable
 * (like RANDOM, SECONDS, LINENO) whose value is unknowable statically.
 */
export function isDynamicBuiltinVariable(varName: string): boolean {
  return DYNAMIC_BUILTIN_VARIABLES.has(varName)
}

/**
 * Returns true if the variable name is a tracked builtin (PWD, BASH_SOURCE,
 * FUNCNAME) that flow analysis may seed with known initial values.
 */
export function isTrackedBuiltinVariable(varName: string): boolean {
  return TRACKED_BUILTIN_VARIABLES.has(varName)
}

/**
 * Get a known initial value for a tracked builtin variable at script start.
 *
 * @param varName The variable name
 * @param fileUri The file:// URI of the script being analyzed
 * @param functionName Optional name of the enclosing function
 * @returns The initial value or null if not known
 */
export function getInitialBuiltinValue(
  varName: string,
  fileUri: string,
  functionName?: string,
): string | null {
  switch (varName) {
    case 'PWD':
      // PWD is the initial working directory; flow analysis tracks subsequent cd calls
      return null // Let the analyzer set this from cwd
    case 'BASH_SOURCE':
      // BASH_SOURCE[0] is the current source file
      return fileUri.replace(/^file:\/\//, '')
    case 'FUNCNAME':
      // FUNCNAME[0] is the current function name
      return functionName || 'main'
    case 'OLDPWD':
      // OLDPWD starts unset
      return null
    default:
      return null
  }
}
